using System.Collections.Generic;
using UnityEngine;

public class Crazy_AttackStatus
{
	public string attackname;

	public string attackanimname;

	public Crazy_AttackType attacktype;

	public float attacktime;

	public bool attackmove;

	public float attackmovebegintime;

	public float attackmoveendtime;

	public float attackmovespeed;

	public float attackmoveacc;

	public bool attackrotate;

	public float nextattacktime;

	public int attackeffectid;

	public float attackrecover;

	public List<Crazy_AttackJudgmentInfo> attackjudgmentinfo;

	public Crazy_AttackEffect attackadveffectdata;

	protected static Dictionary<string, Crazy_AttackStatus> m_info;

	public static void Initialize()
	{
		if (m_info == null)
		{
			m_info = new Dictionary<string, Crazy_AttackStatus>();
			ReadData();
		}
	}

	protected static void ReadData()
	{
		Crazy_AttackStatus crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack01_Sword01";
		crazy_AttackStatus.attackanimname = "Attack01_Sword01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack01;
		crazy_AttackStatus.attacktime = 0.367f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		Crazy_AttackJudgmentInfo crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 75f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 20f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.26f;
		crazy_AttackStatus.attackmoveendtime = 0.33f;
		crazy_AttackStatus.attackmovespeed = 10f;
		crazy_AttackStatus.attackmoveacc = -56f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.367f;
		crazy_AttackStatus.attackeffectid = 0;
		crazy_AttackStatus.attackrecover = 0.3f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack02_Sword01";
		crazy_AttackStatus.attackanimname = "Attack02_Sword01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack02;
		crazy_AttackStatus.attacktime = 0.367f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.167f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 90f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 20f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.1f;
		crazy_AttackStatus.attackmoveendtime = 0.166f;
		crazy_AttackStatus.attackmovespeed = 15f;
		crazy_AttackStatus.attackmoveacc = -70f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.367f;
		crazy_AttackStatus.attackeffectid = 1;
		crazy_AttackStatus.attackrecover = 0.267f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack03_Sword01";
		crazy_AttackStatus.attackanimname = "Attack03_Sword01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack03;
		crazy_AttackStatus.attacktime = 0.5f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.133f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 90f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 20f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.33f;
		crazy_AttackStatus.attackmoveendtime = 0.43f;
		crazy_AttackStatus.attackmovespeed = 25f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.5f;
		crazy_AttackStatus.attackeffectid = 2;
		crazy_AttackStatus.attackrecover = 0.367f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack04_Sword01";
		crazy_AttackStatus.attackanimname = "Attack04_Sword01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack04;
		crazy_AttackStatus.attacktime = 0.6f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.267f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 120f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 20f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = 3;
		crazy_AttackStatus.attackrecover = 0.6f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0.233f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = new Vector3(0f, 1.5f, 0f);
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = true;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Skill01_Sword01";
		crazy_AttackStatus.attackanimname = "Skill01_Sword01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Skill;
		crazy_AttackStatus.attacktime = 1.667f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.567f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 135f;
		crazy_AttackJudgmentInfo.attackdamage = 3f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 20f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = true;
		crazy_AttackStatus.attackmovebegintime = 0.933f;
		crazy_AttackStatus.attackmoveendtime = 1.133f;
		crazy_AttackStatus.attackmovespeed = 40f;
		crazy_AttackStatus.attackmoveacc = -200f;
		crazy_AttackStatus.attackrotate = true;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = -1;
		crazy_AttackStatus.attackrecover = 1.667f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0.1f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = new Vector3(0f, 1.4f, 0f);
		crazy_AttackStatus.attackadveffectdata.shaketime = 0.03f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0.03f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 1f;
		crazy_AttackStatus.attackadveffectdata.isfollow = true;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack01_Hammer01";
		crazy_AttackStatus.attackanimname = "Attack01_Hammer01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack01;
		crazy_AttackStatus.attacktime = 0.6f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.567f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 120f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.14f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackJudgmentInfo.attackshaketime = 0.2f;
		crazy_AttackJudgmentInfo.attackshakeintervaltime = 0.01f;
		crazy_AttackJudgmentInfo.attackshakeamplitude = 2f;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.6f;
		crazy_AttackStatus.attackeffectid = 0;
		crazy_AttackStatus.attackrecover = 0.433f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack02_Hammer01";
		crazy_AttackStatus.attackanimname = "Attack02_Hammer01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack02;
		crazy_AttackStatus.attacktime = 0.6f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.333f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 120f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.14f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackJudgmentInfo.attackshaketime = 0.2f;
		crazy_AttackJudgmentInfo.attackshakeintervaltime = 0.01f;
		crazy_AttackJudgmentInfo.attackshakeamplitude = 2f;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.6f;
		crazy_AttackStatus.attackeffectid = 1;
		crazy_AttackStatus.attackrecover = 0.433f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack03_Hammer01";
		crazy_AttackStatus.attackanimname = "Attack03_Hammer01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack03;
		crazy_AttackStatus.attacktime = 0.6f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.333f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.14f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackJudgmentInfo.attackshaketime = 0.2f;
		crazy_AttackJudgmentInfo.attackshakeintervaltime = 0.01f;
		crazy_AttackJudgmentInfo.attackshakeamplitude = 2f;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.6f;
		crazy_AttackStatus.attackeffectid = 2;
		crazy_AttackStatus.attackrecover = 0.467f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = new Vector3(0f, 0f, 0f);
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack04_Hammer01";
		crazy_AttackStatus.attackanimname = "Attack04_Hammer01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack04;
		crazy_AttackStatus.attacktime = 0.667f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.3f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 4f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.14f;
		crazy_AttackJudgmentInfo.attackshake = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = 3;
		crazy_AttackStatus.attackrecover = 0.467f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0.3f;
		crazy_AttackStatus.attackadveffectdata.effectname = "Fracturing";
		crazy_AttackStatus.attackadveffectdata.delta = new Vector3(0f, 0.1f, 0f);
		crazy_AttackStatus.attackadveffectdata.shaketime = 0.4f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0.01f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 2.5f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Skill01_Hammer01";
		crazy_AttackStatus.attackanimname = "Skill01_Hammer01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Skill;
		crazy_AttackStatus.attacktime = 1.833f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.967f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 4f;
		crazy_AttackJudgmentInfo.attackrange = 7f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 8f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.14f;
		crazy_AttackJudgmentInfo.attackshake = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = true;
		crazy_AttackStatus.attackmovebegintime = 0f;
		crazy_AttackStatus.attackmoveendtime = 0f;
		crazy_AttackStatus.attackmovespeed = 0f;
		crazy_AttackStatus.attackmoveacc = 0f;
		crazy_AttackStatus.attackrotate = true;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = -1;
		crazy_AttackStatus.attackrecover = 1.833f;
		crazy_AttackStatus.attackadveffectdata.begintime = 1.067f;
		crazy_AttackStatus.attackadveffectdata.effectname = "Crack";
		crazy_AttackStatus.attackadveffectdata.delta = new Vector3(0f, 0.1f, 0f);
		crazy_AttackStatus.attackadveffectdata.shaketime = 0.6f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0.01f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 3f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack01_Axe01";
		crazy_AttackStatus.attackanimname = "Attack01_Axe01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack01;
		crazy_AttackStatus.attacktime = 0.667f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.4f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackJudgmentInfo.attackshaketime = 0.2f;
		crazy_AttackJudgmentInfo.attackshakeintervaltime = 0.01f;
		crazy_AttackJudgmentInfo.attackshakeamplitude = 1.5f;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.667f;
		crazy_AttackStatus.attackeffectid = 0;
		crazy_AttackStatus.attackrecover = 0.5f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack02_Axe01";
		crazy_AttackStatus.attackanimname = "Attack02_Axe01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack02;
		crazy_AttackStatus.attacktime = 0.667f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.4f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackJudgmentInfo.attackshaketime = 0.2f;
		crazy_AttackJudgmentInfo.attackshakeintervaltime = 0.01f;
		crazy_AttackJudgmentInfo.attackshakeamplitude = 1.5f;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.667f;
		crazy_AttackStatus.attackeffectid = 1;
		crazy_AttackStatus.attackrecover = 0.5f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack03_Axe01";
		crazy_AttackStatus.attackanimname = "Attack03_Axe01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack03;
		crazy_AttackStatus.attacktime = 0.667f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.333f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 135f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = true;
		crazy_AttackJudgmentInfo.attackshaketime = 0.2f;
		crazy_AttackJudgmentInfo.attackshakeintervaltime = 0.01f;
		crazy_AttackJudgmentInfo.attackshakeamplitude = 1.5f;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0.667f;
		crazy_AttackStatus.attackeffectid = 2;
		crazy_AttackStatus.attackrecover = 0.433f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack04_Axe01";
		crazy_AttackStatus.attackanimname = "Attack04_Axe01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack03;
		crazy_AttackStatus.attacktime = 0.7f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.333f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 5f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = true;
		crazy_AttackJudgmentInfo.attackpausetime = 0.06f;
		crazy_AttackJudgmentInfo.attackshake = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = 3;
		crazy_AttackStatus.attackrecover = 0.5f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0.4f;
		crazy_AttackStatus.attackadveffectdata.effectname = "Fissure";
		crazy_AttackStatus.attackadveffectdata.delta = new Vector3(0f, 0.1f, 0f);
		crazy_AttackStatus.attackadveffectdata.shaketime = 0.2f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0.01f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 2f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Skill01_Axe01";
		crazy_AttackStatus.attackanimname = "Skill01_Axe01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Skill;
		crazy_AttackStatus.attacktime = 2.167f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.667f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1.25f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = true;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.9f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1.25f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = true;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.attackjudgmenttime = 1.2f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1.25f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = true;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.attackjudgmenttime = 1.567f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 7f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1.25f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = true;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = true;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = -1;
		crazy_AttackStatus.attackrecover = 2.167f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0.3f;
		crazy_AttackStatus.attackadveffectdata.effectname = "AxeSkill";
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = true;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack01_Bow01";
		crazy_AttackStatus.attackanimname = "Attack01_Bow01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack01;
		crazy_AttackStatus.attacktime = 1f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 2f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackJudgmentInfo.attackpausetime = 0f;
		crazy_AttackJudgmentInfo.attackshake = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = -1;
		crazy_AttackStatus.attackrecover = 0.5f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0.4f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0.2f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0.01f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 2f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Skill01_Bow01";
		crazy_AttackStatus.attackanimname = "Skill01_Bow01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Skill;
		crazy_AttackStatus.attacktime = 2.4f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 2.4f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 15f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 10f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.1f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.15f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = true;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = true;
		crazy_AttackStatus.attackmovebegintime = 0f;
		crazy_AttackStatus.attackmoveendtime = 0f;
		crazy_AttackStatus.attackmovespeed = 0f;
		crazy_AttackStatus.attackmoveacc = 0f;
		crazy_AttackStatus.attackrotate = true;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = -1;
		crazy_AttackStatus.attackrecover = 2.4f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Attack01_Staff01";
		crazy_AttackStatus.attackanimname = "Attack01_Staff01_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Attack01;
		crazy_AttackStatus.attacktime = 0.6f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = false;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.05f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 5f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 1f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 40f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.25f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.35f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = false;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackJudgmentInfo.attackpausetime = 0f;
		crazy_AttackJudgmentInfo.attackshake = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = false;
		crazy_AttackStatus.attackmovebegintime = 0.23f;
		crazy_AttackStatus.attackmoveendtime = 0.566f;
		crazy_AttackStatus.attackmovespeed = 30f;
		crazy_AttackStatus.attackmoveacc = -120f;
		crazy_AttackStatus.attackrotate = false;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = -1;
		crazy_AttackStatus.attackrecover = 0.4f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0.4f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0.2f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0.01f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 2f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
		crazy_AttackStatus = new Crazy_AttackStatus();
		crazy_AttackStatus.attackname = "Skill01_Staff01";
		crazy_AttackStatus.attackanimname = "Skill01_Start_Staff_merge";
		crazy_AttackStatus.attacktype = Crazy_AttackType.Skill;
		crazy_AttackStatus.attacktime = 12f;
		crazy_AttackStatus.attackjudgmentinfo = new List<Crazy_AttackJudgmentInfo>();
		crazy_AttackJudgmentInfo = new Crazy_AttackJudgmentInfo();
		crazy_AttackJudgmentInfo.usecallback = true;
		crazy_AttackJudgmentInfo.attackjudgmenttime = 0.4f;
		crazy_AttackJudgmentInfo.attackpoint.angle = 0f;
		crazy_AttackJudgmentInfo.attackpoint.length = 0f;
		crazy_AttackJudgmentInfo.attackrange = 4f;
		crazy_AttackJudgmentInfo.attackangle = 180f;
		crazy_AttackJudgmentInfo.attackdamage = 4f;
		crazy_AttackJudgmentInfo.hitdata.beatDir = Vector3.zero;
		crazy_AttackJudgmentInfo.hitdata.beatSpeed = 10f;
		crazy_AttackJudgmentInfo.hitdata.beatTime = 0.1f;
		crazy_AttackJudgmentInfo.hitdata.hitrecovertime = 0.15f;
		crazy_AttackJudgmentInfo.hitdata.crazy_fightedtype = Crazy_FightedType.BeatBack;
		crazy_AttackJudgmentInfo.hitdata.hitrecoverPower = 1f;
		crazy_AttackJudgmentInfo.attackreset = true;
		crazy_AttackJudgmentInfo.attackpause = false;
		crazy_AttackStatus.attackjudgmentinfo.Add(crazy_AttackJudgmentInfo);
		crazy_AttackStatus.attackmove = true;
		crazy_AttackStatus.attackmovebegintime = 0f;
		crazy_AttackStatus.attackmoveendtime = 0f;
		crazy_AttackStatus.attackmovespeed = 0f;
		crazy_AttackStatus.attackmoveacc = 0f;
		crazy_AttackStatus.attackrotate = true;
		crazy_AttackStatus.nextattacktime = 0f;
		crazy_AttackStatus.attackeffectid = -1;
		crazy_AttackStatus.attackrecover = 2.4f;
		crazy_AttackStatus.attackadveffectdata.begintime = 0f;
		crazy_AttackStatus.attackadveffectdata.effectname = string.Empty;
		crazy_AttackStatus.attackadveffectdata.delta = Vector3.zero;
		crazy_AttackStatus.attackadveffectdata.shaketime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeintervaltime = 0f;
		crazy_AttackStatus.attackadveffectdata.shakeamplitude = 0f;
		crazy_AttackStatus.attackadveffectdata.isfollow = false;
		m_info.Add(crazy_AttackStatus.attackname, crazy_AttackStatus);
	}

	public static Dictionary<string, Crazy_AttackStatus> ReadAttackStatusInfo()
	{
		if (m_info == null)
		{
			Initialize();
		}
		return m_info;
	}
}
